using System.IO;
using System.Threading.Tasks;
using CAP_Core.Export;

namespace CAP.Avalonia.Services;

/// <summary>
/// Persists a <see cref="VerilogAExportResult"/> to disk in the layout the
/// generated SPICE test bench expects: component modules go into a
/// <c>components/</c> subdirectory, top-level netlist and test bench go at
/// the root. The test bench's <c>pre_osdi components/&lt;name&gt;.osdi</c>
/// paths resolve directly if the user compiles OSDI files in-place.
/// </summary>
public class VerilogAFileWriter
{
    private const string ComponentsSubdir = "components";

    /// <summary>
    /// Writes all files from <paramref name="result"/> into
    /// <paramref name="outputDirectory"/>. Returns the absolute path to the
    /// generated SPICE test bench (or <c>null</c> if none was produced).
    /// </summary>
    /// <exception cref="IOException">Filesystem error while writing.</exception>
    /// <exception cref="UnauthorizedAccessException">No write permission.</exception>
    public async Task<string?> WriteAsync(VerilogAExportResult result, string outputDirectory)
    {
        var componentsDir = Path.Combine(outputDirectory, ComponentsSubdir);
        Directory.CreateDirectory(componentsDir);

        foreach (var (fileName, content) in result.ComponentFiles)
            await File.WriteAllTextAsync(Path.Combine(componentsDir, fileName), content);

        if (!string.IsNullOrEmpty(result.TopLevelNetlist))
            await File.WriteAllTextAsync(
                Path.Combine(outputDirectory, $"{result.CircuitName}.va"),
                result.TopLevelNetlist);

        string? benchPath = null;
        if (!string.IsNullOrEmpty(result.SpiceTestBench))
        {
            benchPath = Path.Combine(outputDirectory, $"{result.CircuitName}.sp");
            await File.WriteAllTextAsync(benchPath, result.SpiceTestBench);
        }

        await WriteReadmeAsync(result, outputDirectory);
        return benchPath;
    }

    private static async Task WriteReadmeAsync(VerilogAExportResult result, string outputDirectory)
    {
        var readme = $"""
            # Verilog-A Export: {result.CircuitName}
            Generated by Lunima on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC

            ## Files
            - `{ComponentsSubdir}/`       Verilog-A component models (`.va`)
            - `{result.CircuitName}.va`   Top-level circuit netlist (documentation-only;
                                          OpenVAF cannot compile hierarchical netlists)
            - `{result.CircuitName}.sp`   NGSpice+OSDI test bench
            - `README.md`                 This file

            ## Running the test bench

            Compile every component's `.va` to an OSDI binary next to it, then run
            the bench from this directory:

            ```
            for f in {ComponentsSubdir}/*.va; do openvaf "$f"; done
            ngspice -b {result.CircuitName}.sp        # use ngspice_con.exe on Windows
            ```

            The bench preloads each OSDI via `pre_osdi {ComponentsSubdir}/…` and
            instantiates one N-element per component. Port 0 is driven at Re=1V,
            all other ports are terminated with 1 MΩ loads.

            ## Convention
            Optical amplitude is represented as two electrical nodes per port
            (`portN_re` / `portN_im`). Optical power at port N is proportional to
            `V(portN_re)² + V(portN_im)²`.
            """;

        await File.WriteAllTextAsync(Path.Combine(outputDirectory, "README.md"), readme);
    }
}
