using System.Globalization;
using System.Text;
using CAP_Core.Components.Core;
using CAP_Core.Components.Connections;

namespace CAP_Core.Export;

/// <summary>
/// Assembles a PICWave Python script from pre-flattened components and
/// connections. Keeps string-concatenation concerns out of the orchestrator.
/// </summary>
internal static class PicWaveScriptWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    internal static string Write(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        int wavelengthNm,
        double wavelengthMinNm,
        double wavelengthMaxNm,
        int numPoints)
    {
        var sb = new StringBuilder();
        AppendHeader(sb);
        AppendSMatrixData(sb, components, wavelengthNm);
        AppendComponents(sb, components, wavelengthNm);
        AppendConnections(sb, connections);
        AppendSimulation(sb, wavelengthMinNm, wavelengthMaxNm, numPoints);
        AppendPlot(sb);
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("# =============================================================================");
        sb.AppendLine("# Lunima circuit export — PICWave scripting template");
        sb.AppendLine("#");
        sb.AppendLine("# PICWave (Photon Design) exposes a COM-based Python scripting interface that");
        sb.AppendLine("# is not installable from PyPI. This file describes the circuit topology and");
        sb.AppendLine("# S-parameters in a simulator-agnostic shape. To run against a real simulator:");
        sb.AppendLine("#");
        sb.AppendLine("#   - PICWave: replace the imports below with");
        sb.AppendLine("#       import win32com.client");
        sb.AppendLine("#       picwave = win32com.client.Dispatch('PICWave.Application')");
        sb.AppendLine("#     and adapt add_component/connect calls to PICWave's COM methods");
        sb.AppendLine("#     (see the PICWave scripting manual).");
        sb.AppendLine("#");
        sb.AppendLine("#   - Simphony (open-source, pip-installable): the API naming below matches");
        sb.AppendLine("#     Simphony conventions, so this script is runnable after");
        sb.AppendLine("#       pip install simphony");
        sb.AppendLine("#");
        sb.AppendLine("# Generated by Lunima — https://github.com/aignermax/Lunima");
        sb.AppendLine("# =============================================================================");
        sb.AppendLine();
        sb.AppendLine("import numpy as np");
        sb.AppendLine("import matplotlib.pyplot as plt");
        sb.AppendLine();
        sb.AppendLine("# Swap this import for your target simulator's equivalent:");
        sb.AppendLine("from simphony import Circuit");
        sb.AppendLine("from simphony.components import Waveguide, DirectionalCoupler, MMI, GratingCoupler, CustomComponent");
        sb.AppendLine();
        sb.AppendLine("circuit = Circuit()");
        sb.AppendLine();
    }

    private static void AppendSMatrixData(StringBuilder sb, IReadOnlyList<Component> components, int wavelengthNm)
    {
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        bool anyEmitted = false;

        foreach (var comp in components)
        {
            if (comp.WaveLengthToSMatrixMap.Count == 0) continue;

            var varName = PicWaveIdentifier.ForVar(comp);
            if (!emitted.Add(varName)) continue;

            if (!anyEmitted)
            {
                sb.AppendLine("# --- S-matrix data (wavelength in metres; rows indexed by PhysicalPins order) ---");
                anyEmitted = true;
            }

            sb.Append(PicWaveSMatrixEmitter.EmitWavelengthDict(comp, varName));
            sb.AppendLine();
        }
    }

    private static void AppendComponents(StringBuilder sb, IReadOnlyList<Component> components, int wavelengthNm)
    {
        if (components.Count == 0) return;

        sb.AppendLine("# --- Components ---");
        foreach (var comp in components)
        {
            var varName = PicWaveIdentifier.ForVar(comp);

            // Any registered wavelength counts — the downstream sweep interpolates
            // between the points we emit. Requiring an exact match on wavelengthNm
            // would silently discard real wavelength-dependent data when the target
            // happens to fall between grid points (e.g. SiEPIC PDK grating couplers
            // indexed at 1500/1509/1521/.../1600 nm would fall through to a generic
            // typed constructor at wavelengthNm=1550).
            bool hasSMatrix = comp.WaveLengthToSMatrixMap.Count > 0;

            var constructor = PicWaveComponentMapper.Build(comp, hasSMatrix, varName);
            sb.AppendLine($"circuit.add_component('{varName}', {constructor})");
        }
        sb.AppendLine();
    }

    private static void AppendConnections(StringBuilder sb, IReadOnlyList<WaveguideConnection> connections)
    {
        if (connections.Count == 0) return;

        sb.AppendLine("# --- Connections ---");
        foreach (var conn in connections)
        {
            var startComp = PicWaveIdentifier.ForVar(conn.StartPin.ParentComponent);
            var endComp = PicWaveIdentifier.ForVar(conn.EndPin.ParentComponent);
            sb.AppendLine($"circuit.connect('{startComp}', '{conn.StartPin.Name}', '{endComp}', '{conn.EndPin.Name}')");
        }
        sb.AppendLine();
    }

    private static void AppendSimulation(StringBuilder sb, double wlMinNm, double wlMaxNm, int numPoints)
    {
        sb.AppendLine("# --- Wavelength sweep ---");
        sb.AppendLine($"wavelengths = np.linspace({wlMinNm.ToString(Inv)}e-9, {wlMaxNm.ToString(Inv)}e-9, {numPoints})");
        sb.AppendLine();
        sb.AppendLine("# Fill in the port names of your design's external input/output (use the");
        sb.AppendLine("# component variable names printed above). Leaving these empty will raise at runtime.");
        sb.AppendLine("INPUT_PORTS = {}   # e.g. {'gc_in': 1.0}");
        sb.AppendLine("OUTPUT_PORTS = []  # e.g. ['gc_out']");
        sb.AppendLine();
        sb.AppendLine("if not INPUT_PORTS or not OUTPUT_PORTS:");
        sb.AppendLine("    raise ValueError('Set INPUT_PORTS and OUTPUT_PORTS before running the sweep.')");
        sb.AppendLine();
        sb.AppendLine("results = circuit.simulate(");
        sb.AppendLine("    wavelengths=wavelengths,");
        sb.AppendLine("    input_ports=INPUT_PORTS,");
        sb.AppendLine("    output_ports=OUTPUT_PORTS,");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void AppendPlot(StringBuilder sb)
    {
        sb.AppendLine("# --- Plot transmission spectrum ---");
        sb.AppendLine("plt.figure(figsize=(10, 6))");
        sb.AppendLine("if isinstance(results, dict) and 'power_out' in results:");
        sb.AppendLine("    for port, power in results['power_out'].items():");
        sb.AppendLine("        plt.plot(wavelengths * 1e9, 10 * np.log10(np.maximum(power, 1e-15)), label=port)");
        sb.AppendLine("plt.xlabel('Wavelength (nm)')");
        sb.AppendLine("plt.ylabel('Transmission (dB)')");
        sb.AppendLine("plt.legend()");
        sb.AppendLine("plt.grid(True)");
        sb.AppendLine("plt.title('Photonic Circuit Transmission Spectrum')");
        sb.AppendLine("plt.tight_layout()");
        sb.AppendLine("plt.show()");
    }
}

/// <summary>
/// Produces a Python-identifier-safe variable name from a <see cref="Component"/>.
/// Digits at the start are prefixed with <c>_</c>; non-alphanumeric runs collapse
/// to a single underscore.
/// </summary>
internal static class PicWaveIdentifier
{
    internal static string ForVar(Component comp)
    {
        var source = comp.Identifier ?? comp.Name ?? "comp";
        if (string.IsNullOrWhiteSpace(source)) return "comp";

        var sb = new StringBuilder(source.Length);
        foreach (var ch in source)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');

        var result = sb.ToString();
        return char.IsDigit(result[0]) ? "_" + result : result;
    }
}
