using System.Globalization;
using System.Text;
using CAP_Core.Components;
using CAP_Core.Components.Core;
using CAP_Core.Components.Connections;

namespace CAP_Core.Export;

/// <summary>
/// Assembles a runnable sax-based Python script from pre-flattened components
/// and connections. sax (https://flaport.github.io/sax/) is the S-parameter
/// library that Simphony 0.7+ builds on; targeting it directly gives us a
/// script that runs after <c>pip install sax numpy matplotlib</c> without
/// depending on a specific Simphony version's public surface.
/// </summary>
internal static class PicWaveScriptWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    internal static string Write(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        int wavelengthNm,
        double wavelengthMinNm,
        double wavelengthMaxNm,
        int numPoints)
    {
        var resolvedConnections = connections
            .Select(c => new ResolvedConnection(
                ResolveToLeafPin(c.StartPin),
                ResolveToLeafPin(c.EndPin)))
            .ToList();

        var sb = new StringBuilder();
        AppendHeader(sb);
        AppendImports(sb);
        PicWaveSMatrixEmitter.AppendAll(sb, components);
        PicWaveModelEmitter.AppendModels(sb, components, wavelengthNm);
        PicWaveNetlistEmitter.AppendNetlistAndSweep(
            sb, components, resolvedConnections,
            wavelengthMinNm, wavelengthMaxNm, numPoints);
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("# =============================================================================");
        sb.AppendLine("# Lunima circuit export — sax / Simphony-compatible Python");
        sb.AppendLine("#");
        sb.AppendLine("# This script builds the exported photonic circuit as a sax netlist, runs a");
        sb.AppendLine("# wavelength sweep, and plots the transmission between the chosen ports.");
        sb.AppendLine("#");
        sb.AppendLine("# Runs after:");
        sb.AppendLine("#   pip install sax numpy matplotlib");
        sb.AppendLine("#");
        sb.AppendLine("# sax is the S-parameter library that Simphony 0.7+ uses internally for");
        sb.AppendLine("# classical-circuit simulation. For the commercial PICWave (Photon Design)");
        sb.AppendLine("# COM interface, adapt the netlist below to PICWave's scripting API —");
        sb.AppendLine("# the component/connection structure is the same.");
        sb.AppendLine("#");
        sb.AppendLine("# Generated by Lunima — https://github.com/aignermax/Lunima");
        sb.AppendLine("# =============================================================================");
        sb.AppendLine();
    }

    private static void AppendImports(StringBuilder sb)
    {
        sb.AppendLine("import numpy as np");
        sb.AppendLine("import matplotlib.pyplot as plt");
        sb.AppendLine("import jax.numpy as jnp");
        sb.AppendLine("import sax");
        sb.AppendLine();
    }

    /// <summary>
    /// If <paramref name="pin"/> belongs to a <see cref="ComponentGroup"/>,
    /// unwrap through its matching <see cref="GroupPin"/> to the leaf
    /// <see cref="PhysicalPin"/>. Groups are flattened before emission, so a
    /// connection authored against a group's outward-facing pin would
    /// otherwise reference a var that was never added to the netlist.
    /// </summary>
    internal static PhysicalPin ResolveToLeafPin(PhysicalPin pin)
    {
        const int maxDepth = 16;
        var current = pin;
        for (int depth = 0; depth < maxDepth; depth++)
        {
            if (current.ParentComponent is not ComponentGroup group)
                return current;

            var match = group.ExternalPins.FirstOrDefault(ep => ep.Name == current.Name);
            if (match == null)
                throw new InvalidOperationException(
                    $"Connection references pin '{current.Name}' on group " +
                    $"'{group.Identifier ?? group.Name}', but no matching external " +
                    "pin exists on that group. The design may be corrupted; re-save " +
                    "the group or reconnect the pin.");

            current = match.InternalPin;
        }
        throw new InvalidOperationException(
            $"Pin '{pin.Name}' is nested in groups beyond {maxDepth} levels — " +
            "the design's ComponentGroup structure appears to be cyclic.");
    }
}

/// <summary>
/// A connection whose endpoints have already been resolved through any
/// ComponentGroup layers, so <c>Start.ParentComponent</c> and
/// <c>End.ParentComponent</c> are guaranteed to be leaf components.
/// </summary>
internal readonly record struct ResolvedConnection(PhysicalPin Start, PhysicalPin End);

/// <summary>
/// Produces a Python-identifier-safe variable name from a <see cref="Component"/>.
/// Digits at the start are prefixed with <c>_</c>; non-alphanumeric runs collapse
/// to a single underscore.
/// </summary>
internal static class PicWaveIdentifier
{
    internal static string ForVar(Component comp)
    {
        var source = comp.Identifier ?? comp.Name ?? "comp";
        if (string.IsNullOrWhiteSpace(source)) return "comp";

        var sb = new StringBuilder(source.Length);
        foreach (var ch in source)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');

        var result = sb.ToString();
        return char.IsDigit(result[0]) ? "_" + result : result;
    }

    /// <summary>
    /// Sanitises a pin name for use as a sax port identifier. sax port names
    /// must be valid Python identifiers; Lunima pin names like "a0", "in", "out1"
    /// already are, but defensive sanitisation handles edge cases cheaply.
    /// </summary>
    internal static string ForPin(string pinName)
    {
        if (string.IsNullOrWhiteSpace(pinName)) return "p";

        var sb = new StringBuilder(pinName.Length);
        foreach (var ch in pinName)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');

        var result = sb.ToString();
        return char.IsDigit(result[0]) ? "p_" + result : result;
    }
}
