using System.Globalization;
using System.Text;
using CAP_Core.Components;
using CAP_Core.Components.Core;
using CAP_Core.Components.Connections;
using CAP_Core.LightCalculation;

namespace CAP_Core.Export;

/// <summary>
/// Exports Lunima designs to PICWave-compatible Python circuit simulator scripts.
/// Generates Python code that uses a PICWave-style API for wavelength-domain simulation.
/// </summary>
public class PicWaveExporter
{
    private static readonly CultureInfo Ci = CultureInfo.InvariantCulture;

    /// <summary>Minimum wavelength for the default sweep in nanometers.</summary>
    public const double DefaultWavelengthMinNm = 1500.0;

    /// <summary>Maximum wavelength for the default sweep in nanometers.</summary>
    public const double DefaultWavelengthMaxNm = 1600.0;

    /// <summary>Default number of wavelength sweep points.</summary>
    public const int DefaultNumPoints = 100;

    /// <summary>
    /// Exports the design to a PICWave Python script.
    /// </summary>
    /// <param name="components">Flat list of components on the canvas.</param>
    /// <param name="connections">Waveguide connections between pins.</param>
    /// <param name="wavelengthMinNm">Sweep minimum wavelength in nm.</param>
    /// <param name="wavelengthMaxNm">Sweep maximum wavelength in nm.</param>
    /// <param name="numPoints">Number of sweep wavelength points.</param>
    /// <returns>Python script as a string.</returns>
    public string Export(
        IEnumerable<Component> components,
        IEnumerable<WaveguideConnection> connections,
        double wavelengthMinNm = DefaultWavelengthMinNm,
        double wavelengthMaxNm = DefaultWavelengthMaxNm,
        int numPoints = DefaultNumPoints)
    {
        var allComponents = FlattenComponents(components).ToList();
        var allConnections = connections.ToList();

        var sb = new StringBuilder();
        AppendHeader(sb);
        AppendComponents(sb, allComponents);
        AppendConnections(sb, allConnections);
        AppendSimulation(sb, wavelengthMinNm, wavelengthMaxNm, numPoints);
        AppendPlot(sb);
        return sb.ToString();
    }

    /// <summary>
    /// Flattens ComponentGroups into their leaf components.
    /// </summary>
    private static IEnumerable<Component> FlattenComponents(IEnumerable<Component> components)
    {
        foreach (var comp in components)
        {
            if (comp is ComponentGroup group)
            {
                foreach (var child in group.GetAllComponentsRecursive())
                    yield return child;
            }
            else
            {
                yield return comp;
            }
        }
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("# PICWave circuit simulation script");
        sb.AppendLine("# Generated by Lunima — https://github.com/aignermax/Lunima");
        sb.AppendLine();
        sb.AppendLine("import numpy as np");
        sb.AppendLine("import matplotlib.pyplot as plt");
        sb.AppendLine();
        sb.AppendLine("# ---------------------------------------------------------------------------");
        sb.AppendLine("# NOTE: Install PICWave or a compatible simulator before running this script.");
        sb.AppendLine("# Compatible simulators: PICWave, Simphony, SAX");
        sb.AppendLine("# Example: pip install simphony");
        sb.AppendLine("# ---------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("try:");
        sb.AppendLine("    from picwave import Circuit");
        sb.AppendLine("    from picwave.components import Waveguide, DirectionalCoupler, MMI, GratingCoupler, CustomComponent");
        sb.AppendLine("except ImportError:");
        sb.AppendLine("    raise ImportError(\"PICWave not found. Install it via: pip install picwave\")");
        sb.AppendLine();
        sb.AppendLine("# Circuit definition");
        sb.AppendLine("circuit = Circuit()");
        sb.AppendLine();
    }

    private static void AppendComponents(StringBuilder sb, IReadOnlyList<Component> components)
    {
        if (components.Count == 0)
            return;

        sb.AppendLine("# --- Components ---");

        foreach (var comp in components)
        {
            var varName = ToVarName(comp.Identifier);
            var constructor = BuildComponentConstructor(comp);
            sb.AppendLine($"circuit.add_component('{varName}', {constructor})");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Maps a Lunima component to a PICWave constructor call string.
    /// Uses NazcaFunctionName heuristics to identify component types.
    /// </summary>
    private static string BuildComponentConstructor(Component comp)
    {
        var name = (comp.NazcaFunctionName ?? comp.Identifier).ToLowerInvariant();

        if (IsDirectionalCoupler(name))
            return "DirectionalCoupler(coupling=0.5)";

        if (IsGratingCoupler(name))
            return "GratingCoupler()";

        if (IsMmi(name))
            return $"MMI(ports={comp.PhysicalPins.Count})";

        if (IsWaveguide(name))
            return $"Waveguide(length={comp.WidthMicrometers.ToString("F2", Ci)}e-6, loss=2.0)";

        return BuildCustomComponent(comp);
    }

    /// <summary>
    /// Builds a CustomComponent constructor, embedding S-matrix data when available.
    /// Falls back to a placeholder when no S-matrix data is present.
    /// </summary>
    private static string BuildCustomComponent(Component comp)
    {
        int numPorts = comp.PhysicalPins.Count;
        if (numPorts < 1)
            numPorts = 2;

        if (comp.WaveLengthToSMatrixMap.Count > 0)
            return $"CustomComponent(s_matrices=_s_{ToVarName(comp.Identifier)}, num_ports={numPorts})";

        // No S-matrix: generate identity-like placeholder
        return $"CustomComponent(num_ports={numPorts})  # No S-matrix available";
    }

    private static void AppendConnections(StringBuilder sb, IReadOnlyList<WaveguideConnection> connections)
    {
        if (connections.Count == 0)
            return;

        sb.AppendLine("# --- Connections ---");

        // Emit S-matrix data for custom components referenced in connections
        AppendSMatrixData(sb, connections);

        foreach (var conn in connections)
        {
            var startComp = ToVarName(conn.StartPin.ParentComponent.Identifier);
            var startPin = conn.StartPin.Name;
            var endComp = ToVarName(conn.EndPin.ParentComponent.Identifier);
            var endPin = conn.EndPin.Name;

            sb.AppendLine($"circuit.connect('{startComp}', '{startPin}', '{endComp}', '{endPin}')");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Emits S-matrix dictionaries for components that carry wavelength-indexed S-matrix data.
    /// </summary>
    private static void AppendSMatrixData(StringBuilder sb, IReadOnlyList<WaveguideConnection> connections)
    {
        var visited = new HashSet<string>(StringComparer.Ordinal);

        foreach (var conn in connections)
        {
            AppendSMatrixForComponent(sb, conn.StartPin.ParentComponent, visited);
            AppendSMatrixForComponent(sb, conn.EndPin.ParentComponent, visited);
        }
    }

    private static void AppendSMatrixForComponent(
        StringBuilder sb, Component comp, HashSet<string> visited)
    {
        if (comp.WaveLengthToSMatrixMap.Count == 0)
            return;

        var varName = ToVarName(comp.Identifier);
        if (!visited.Add(varName))
            return;

        sb.AppendLine($"# S-matrix data for '{varName}' (wavelength in metres)");
        sb.AppendLine($"_s_{varName} = {{");

        foreach (var (wlNm, sMatrix) in comp.WaveLengthToSMatrixMap)
        {
            double wlM = wlNm * 1e-9;
            sb.AppendLine($"    {wlM.ToString("G4", Ci)}: np.array([");

            AppendSMatrixRows(sb, sMatrix);

            sb.AppendLine("    ]),");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendSimulation(
        StringBuilder sb, double wlMinNm, double wlMaxNm, int numPoints)
    {
        sb.AppendLine("# --- Wavelength sweep ---");
        sb.AppendLine($"wavelengths = np.linspace({wlMinNm.ToString(Ci)}e-9, {wlMaxNm.ToString(Ci)}e-9, {numPoints})");
        sb.AppendLine();
        sb.AppendLine("results = circuit.simulate(");
        sb.AppendLine("    wavelengths=wavelengths,");
        sb.AppendLine("    # Specify input port: e.g. input_ports={'gc_in': 1.0}");
        sb.AppendLine("    # Specify output ports: e.g. output_ports=['gc_out']");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void AppendPlot(StringBuilder sb)
    {
        sb.AppendLine("# --- Plot transmission spectrum ---");
        sb.AppendLine("plt.figure(figsize=(10, 6))");
        sb.AppendLine("if isinstance(results, dict) and 'power_out' in results:");
        sb.AppendLine("    for port, power in results['power_out'].items():");
        sb.AppendLine("        plt.plot(wavelengths * 1e9, 10 * np.log10(np.maximum(power, 1e-15)), label=port)");
        sb.AppendLine("plt.xlabel('Wavelength (nm)')");
        sb.AppendLine("plt.ylabel('Transmission (dB)')");
        sb.AppendLine("plt.legend()");
        sb.AppendLine("plt.grid(True)");
        sb.AppendLine("plt.title('Photonic Circuit Transmission Spectrum')");
        sb.AppendLine("plt.tight_layout()");
        sb.AppendLine("plt.show()");
    }

    /// <summary>
    /// Emits numpy array rows for an SMatrix's complex values.
    /// </summary>
    private static void AppendSMatrixRows(StringBuilder sb, SMatrix sMatrix)
    {
        var mat = sMatrix.SMat;
        for (int r = 0; r < mat.RowCount; r++)
        {
            var rowStr = string.Join(", ",
                Enumerable.Range(0, mat.ColumnCount).Select(c =>
                {
                    var v = mat[r, c];
                    var sign = v.Imaginary >= 0 ? "+" : "";
                    return $"{v.Real.ToString("G6", Ci)}{sign}{v.Imaginary.ToString("G6", Ci)}j";
                }));
            sb.AppendLine($"        [{rowStr}],");
        }
    }

    // --- component type heuristics ---

    private static bool IsWaveguide(string name) =>
        name.Contains("straight") || name.Contains("waveguide") || name.Contains("strt") || name.Contains("wg_");

    private static bool IsDirectionalCoupler(string name) =>
        name.Contains("dc_") || name.Contains("directional") || name.Contains("coupler") || name.Contains("halfring");

    private static bool IsMmi(string name) =>
        name.Contains("mmi") || name.Contains("splitter") || name.Contains("1x2") || name.Contains("2x2") || name.Contains("y_");

    private static bool IsGratingCoupler(string name) =>
        name.Contains("gc_") || name.Contains("grating");

    /// <summary>
    /// Converts a component identifier to a safe Python variable name.
    /// </summary>
    public static string ToVarName(string identifier)
    {
        if (string.IsNullOrWhiteSpace(identifier))
            return "comp";

        var sb = new StringBuilder(identifier.Length);
        foreach (var ch in identifier)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');

        var result = sb.ToString();
        return char.IsDigit(result[0]) ? "_" + result : result;
    }
}
