using System.Globalization;
using System.Numerics;
using System.Text;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Emits per-component S-matrix data as Python wavelength-indexed dictionaries
/// of numpy arrays. One <c>_s_&lt;varname&gt;</c> dict is emitted per component
/// that carries registered S-parameters — the sax model function generated by
/// <see cref="SaxModelEmitter"/> looks up this dict at runtime via
/// nearest-measured-wavelength.
/// </summary>
internal static class SaxSMatrixEmitter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    /// <summary>
    /// Appends <c>_s_&lt;varname&gt;</c> dicts for every component that has
    /// registered S-matrix data. Components without measured data produce
    /// nothing here — their model function (if any) will be purely analytic.
    /// </summary>
    internal static void AppendAll(StringBuilder sb, IReadOnlyList<Component> components)
    {
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        bool anyEmitted = false;

        foreach (var comp in components)
        {
            if (comp.WaveLengthToSMatrixMap.Count == 0) continue;

            var varName = SaxIdentifier.ForVar(comp);
            if (!emitted.Add(varName)) continue;

            if (!anyEmitted)
            {
                sb.AppendLine("# ── Measured S-matrix data ──────────────────────────────────────────");
                sb.AppendLine("# Keys are wavelengths in metres; rows and columns follow the component's");
                sb.AppendLine("# PhysicalPins order at export time.");
                anyEmitted = true;
            }

            sb.Append(EmitWavelengthDict(comp, varName));
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Emits a Python dictionary literal mapping wavelength (m) → numpy complex
    /// 2D array for every wavelength registered on the component.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// A registered wavelength has an S-matrix that does not line up with the
    /// component's PhysicalPins (see <see cref="PirSMatrixExtractor.TryExtract"/>).
    /// </exception>
    internal static string EmitWavelengthDict(Component comp, string varName)
    {
        var sb = new StringBuilder();
        int n = comp.PhysicalPins.Count;
        sb.AppendLine($"_s_{varName} = {{");

        foreach (var wlNm in comp.WaveLengthToSMatrixMap.Keys)
        {
            var matrix = PirSMatrixExtractor.TryExtract(comp, wlNm)
                ?? throw new InvalidOperationException(
                    $"Internal inconsistency: wavelength {wlNm}nm is registered on " +
                    $"'{comp.Name}' but TryExtract returned null.");

            double wlM = wlNm * 1e-9;
            sb.AppendLine($"    {wlM.ToString("G6", Inv)}: np.array([");
            for (int r = 0; r < n; r++)
            {
                var row = new StringBuilder();
                for (int c = 0; c < n; c++)
                {
                    if (c > 0) row.Append(", ");
                    var v = matrix.TryGetValue((r, c), out var cv) ? cv : Complex.Zero;
                    var sign = v.Imaginary >= 0 ? "+" : "";
                    row.Append($"{v.Real.ToString("G6", Inv)}{sign}{v.Imaginary.ToString("G6", Inv)}j");
                }
                sb.AppendLine($"        [{row}],");
            }
            sb.AppendLine("    ]),");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
