using System.Text;
using CAP_Core.Components.Connections;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Writes the top-level Verilog-A netlist and SPICE test bench for a Lunima design.
/// Each optical connection is represented by a twin-node pair (<c>n_re</c>/<c>n_im</c>)
/// matching the complex amplitude convention used by <see cref="VerilogAModuleWriter"/>.
/// Shared nodes for connected pins; unconnected pins become external port pairs.
/// </summary>
internal static class VerilogANetlistWriter
{
    internal static (string Netlist, List<string> ExternalPorts) WriteTopLevel(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        string circuitName)
    {
        var nodeMap = BuildNodeMap(components, connections, out var externalPorts);
        var sb = new StringBuilder();

        sb.AppendLine($"// Top-level Verilog-A netlist: {circuitName}");
        sb.AppendLine($"// Generated by Lunima on {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine($"// Twin-node complex model: each optical port = two nodes (_re / _im).");
        sb.AppendLine();

        foreach (var moduleName in components.Select(VerilogAIdentifier.For).Distinct())
            sb.AppendLine($"`include \"{moduleName}.va\"");
        sb.AppendLine();

        var extPortList = string.Join(", ", externalPorts);
        sb.AppendLine($"module {circuitName}({extPortList});");
        foreach (var port in externalPorts)
            sb.AppendLine($"    electrical {port};");

        var extPortSet = new HashSet<string>(externalPorts);
        var internalNodes = nodeMap.Values
            .SelectMany(d => d.Values)
            .SelectMany(n => new[] { n.Re, n.Im })
            .Distinct()
            .Where(n => !extPortSet.Contains(n))
            .ToList();

        if (internalNodes.Count > 0)
            sb.AppendLine($"    electrical {string.Join(", ", internalNodes)};");
        sb.AppendLine();

        for (int i = 0; i < components.Count; i++)
        {
            var comp = components[i];
            var modName = VerilogAIdentifier.For(comp);
            var ports = comp.PhysicalPins
                .Select((_, idx) => nodeMap[i][idx])
                .SelectMany(n => new[] { n.Re, n.Im })
                .ToList();
            sb.AppendLine($"    {modName} inst_{i}({string.Join(", ", ports)});  // {comp.Name}");
        }

        sb.AppendLine("endmodule");
        return (sb.ToString(), externalPorts);
    }

    private static Dictionary<int, Dictionary<int, (string Re, string Im)>> BuildNodeMap(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        out List<string> externalPorts)
    {
        var nodeMap = new Dictionary<int, Dictionary<int, (string Re, string Im)>>();
        int nodeCounter = 0;

        for (int i = 0; i < components.Count; i++)
        {
            nodeMap[i] = new Dictionary<int, (string, string)>();
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
            {
                nodeMap[i][j] = ($"n{nodeCounter}_re", $"n{nodeCounter}_im");
                nodeCounter++;
            }
        }

        foreach (var conn in connections)
        {
            var (startCompIdx, startPinIdx) = FindPinIndex(components, conn.StartPin);
            var (endCompIdx, endPinIdx) = FindPinIndex(components, conn.EndPin);

            if (startCompIdx < 0)
                throw new InvalidOperationException(
                    $"Connection start pin does not belong to any exported component. " +
                    $"Pin '{conn.StartPin.Name}' (id {conn.StartPin.PinId}) is orphan.");
            if (endCompIdx < 0)
                throw new InvalidOperationException(
                    $"Connection end pin does not belong to any exported component. " +
                    $"Pin '{conn.EndPin.Name}' (id {conn.EndPin.PinId}) is orphan.");

            var sharedNode = nodeMap[startCompIdx][startPinIdx];
            nodeMap[endCompIdx][endPinIdx] = sharedNode;
        }

        var connectedPins = new HashSet<Guid>(
            connections.SelectMany(c => new[] { c.StartPin.PinId, c.EndPin.PinId }));

        externalPorts = new List<string>();
        int portCounter = 0;
        for (int i = 0; i < components.Count; i++)
        {
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
            {
                var pin = components[i].PhysicalPins[j];
                if (!connectedPins.Contains(pin.PinId))
                {
                    nodeMap[i][j] = ($"ext_port{portCounter}_re", $"ext_port{portCounter}_im");
                    externalPorts.Add($"ext_port{portCounter}_re");
                    externalPorts.Add($"ext_port{portCounter}_im");
                    portCounter++;
                }
            }
        }

        return nodeMap;
    }

    private static (int CompIdx, int PinIdx) FindPinIndex(
        IReadOnlyList<Component> components, PhysicalPin pin)
    {
        for (int i = 0; i < components.Count; i++)
        {
            var idx = components[i].PhysicalPins.IndexOf(pin);
            if (idx >= 0) return (i, idx);
        }
        return (-1, -1);
    }

    /// <summary>
    /// Writes an NGSpice+OSDI batch bench. OpenVAF compiles each component's
    /// <c>.va</c> to a standalone <c>.osdi</c>; the bench preloads every unique
    /// OSDI, instantiates one N-element per component with shared-node wiring,
    /// and drives port 0 at 1V. Multi-component designs work because node names
    /// come straight from <c>BuildNodeMap</c>, which already merges connected pins.
    /// </summary>
    internal static string WriteSpiceTestBench(
        string circuitName,
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections)
    {
        var nodeMap = BuildNodeMap(components, connections, out var externalPorts);

        if (externalPorts.Count == 0)
        {
            throw new InvalidOperationException(
                "Cannot generate a SPICE test bench: the circuit has no external ports. " +
                "Every pin is wired to another component, so there is nowhere to inject a " +
                "stimulus or probe an output.");
        }

        var sb = new StringBuilder();
        sb.AppendLine($"* SPICE test bench for {circuitName}");
        sb.AppendLine($"* Generated by Lunima — {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine("* Complex optical model: each optical port = two electrical nodes (_re / _im).");
        sb.AppendLine("* Stimulus: port 0 driven Re=1V, Im=0V. Other ports terminated via 1MΩ loads.");
        sb.AppendLine("*");
        sb.AppendLine("* Prerequisite: compile each component .va file to an OSDI module:");
        foreach (var moduleName in components.Select(VerilogAIdentifier.For).Distinct())
            sb.AppendLine($"*   openvaf {moduleName}.va     ->  {moduleName}.osdi");
        sb.AppendLine("* Then run this bench with NGSpice in batch mode:");
        sb.AppendLine($"*   ngspice -b {circuitName}.sp   (use ngspice_con.exe on Windows)");
        sb.AppendLine();

        // externalPorts comes in (_re, _im) pairs — two entries per optical port.
        int portIdx = 0;
        for (int i = 0; i < externalPorts.Count; i += 2)
        {
            if (portIdx == 0)
            {
                sb.AppendLine($"V{portIdx + 1}_re {externalPorts[i]} 0 DC 1.0");
                sb.AppendLine($"V{portIdx + 1}_im {externalPorts[i + 1]} 0 DC 0.0");
            }
            else
            {
                sb.AppendLine($"Rload{portIdx}_re {externalPorts[i]} 0 1e6");
                sb.AppendLine($"Rload{portIdx}_im {externalPorts[i + 1]} 0 1e6");
            }
            portIdx++;
        }
        sb.AppendLine();

        // One N-element per component, wired via the shared node map.
        // OpenVAF only compiles flat compact models, so we cannot instantiate the
        // hierarchical top-level .va — we must reference each component's OSDI directly.
        var uniqueModules = new HashSet<string>(StringComparer.Ordinal);
        for (int i = 0; i < components.Count; i++)
        {
            var modName = VerilogAIdentifier.For(components[i]);
            uniqueModules.Add(modName);
            var ports = components[i].PhysicalPins
                .Select((_, idx) => nodeMap[i][idx])
                .SelectMany(n => new[] { n.Re, n.Im })
                .ToList();
            sb.AppendLine($"N_inst{i} {string.Join(" ", ports)} {modName}_mod");
            sb.AppendLine($".model {modName}_mod {modName}");
        }
        sb.AppendLine();

        sb.AppendLine(".control");
        foreach (var modName in uniqueModules)
            sb.AppendLine($"  pre_osdi {modName}.osdi");
        sb.AppendLine("  op");
        sb.AppendLine($"  print {string.Join(" ", externalPorts.Select(p => $"v({p})"))}");
        sb.AppendLine("  quit");
        sb.AppendLine(".endc");
        sb.AppendLine(".end");

        return sb.ToString();
    }
}

/// <summary>
/// Produces a Verilog-identifier-safe name from a <see cref="Component"/>.
/// Uses <c>NazcaFunctionName</c> when present, otherwise <c>Name</c>.
/// Non-alphanumeric characters become underscores.
/// </summary>
internal static class VerilogAIdentifier
{
    internal static string For(Component comp)
    {
        var name = comp.NazcaFunctionName ?? comp.Name ?? "component";
        return System.Text.RegularExpressions.Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
    }
}
