using System.Globalization;
using System.Numerics;
using System.Text;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Writes a single Verilog-A module for one photonic component using the
/// twin-node complex amplitude model. Each optical port N is represented by
/// two electrical nodes (<c>portN_re</c> / <c>portN_im</c>) carrying the real
/// and imaginary parts of the complex field amplitude. Transfer equations
/// implement full complex S-matrix multiplication Y = S·X, preserving phase.
/// Falls back to a physically-reasonable heuristic for 2-/3-/4-port components
/// with a loud warning when no S-matrix is available.
/// </summary>
internal static class VerilogAModuleWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    // Heuristic transmission amplitudes used when no S-matrix is available.
    private const double WaveguideThroughputLossy = 0.95;     // Lossy straight waveguide (≈ 0.45 dB/segment)
    private const double WaveguideThroughputIdeal = 0.99;     // Near-ideal 2-port element
    private static readonly double SplitAmplitude5050 = Math.Sqrt(0.5);  // 50/50 power splitter

    internal static string Write(Component comp, string moduleName, int wavelengthNm)
    {
        var pins = comp.PhysicalPins;
        var portList = BuildPortList(pins.Count);
        var (sParams, usedHeuristic) = ExtractSParameters(comp, wavelengthNm);

        var sb = new StringBuilder();
        sb.AppendLine("`include \"disciplines.vams\"");
        sb.AppendLine();
        AppendComplexModelHeader(sb);
        sb.AppendLine($"// Generated by Lunima — Component: {comp.Name}");
        if (!string.IsNullOrEmpty(comp.NazcaFunctionName))
            sb.AppendLine($"// PDK function: {comp.NazcaFunctionName}");
        sb.AppendLine($"// Ports: {pins.Count} | Wavelength: {wavelengthNm}nm");
        if (usedHeuristic)
        {
            sb.AppendLine("// WARNING: No S-matrix was available for this component at the given");
            sb.AppendLine($"//          wavelength ({wavelengthNm}nm). The transfer equations below");
            sb.AppendLine("//          are a lossless-coupler HEURISTIC — verify before trusting the");
            sb.AppendLine("//          simulation result. Provide measured or simulated S-parameters");
            sb.AppendLine("//          in the Lunima model to remove this approximation.");
        }
        sb.AppendLine();
        sb.AppendLine($"module {moduleName}({portList});");

        AppendPortDeclarations(sb, pins);
        sb.AppendLine();
        AppendSParameters(sb, sParams, pins.Count);
        sb.AppendLine("    analog begin");
        AppendTransferEquations(sb, pins.Count);
        sb.AppendLine("    end");
        sb.AppendLine("endmodule");

        return sb.ToString();
    }

    private static void AppendComplexModelHeader(StringBuilder sb)
    {
        sb.AppendLine("// ======================================================================");
        sb.AppendLine("// Complex optical port model — Lunima twin-node convention:");
        sb.AppendLine("//   Each optical port N is represented by two electrical nodes:");
        sb.AppendLine("//     portN_re — real part of the complex field amplitude");
        sb.AppendLine("//     portN_im — imaginary part of the complex field amplitude");
        sb.AppendLine("//   Transfer equations implement S-matrix multiplication Y = S·X:");
        sb.AppendLine("//     Y_re = Σ_j (S_ij_re · X_j_re − S_ij_im · X_j_im)");
        sb.AppendLine("//     Y_im = Σ_j (S_ij_re · X_j_im + S_ij_im · X_j_re)");
        sb.AppendLine("//   Optical power at port N: P ∝ V(portN_re)² + V(portN_im)²");
        sb.AppendLine("// ======================================================================");
        sb.AppendLine();
    }

    private static string BuildPortList(int n)
        => string.Join(", ", Enumerable.Range(0, n).SelectMany(i => new[] { $"port{i}_re", $"port{i}_im" }));

    private static void AppendPortDeclarations(StringBuilder sb, IList<PhysicalPin> pins)
    {
        for (int i = 0; i < pins.Count; i++)
            sb.AppendLine($"    inout port{i}_re, port{i}_im;");
        for (int i = 0; i < pins.Count; i++)
            sb.AppendLine($"    electrical port{i}_re, port{i}_im;  // {pins[i].Name}");
    }

    private static void AppendSParameters(StringBuilder sb, Dictionary<(int, int), Complex> sParams, int n)
    {
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++)
            {
                var s = sParams.TryGetValue((i, j), out var val) ? val : Complex.Zero;
                sb.AppendLine($"    parameter real s{i + 1}{j + 1}_re = {s.Real.ToString("G6", Inv)};");
                sb.AppendLine($"    parameter real s{i + 1}{j + 1}_im = {s.Imaginary.ToString("G6", Inv)};");
            }
        sb.AppendLine();
    }

    private static void AppendTransferEquations(StringBuilder sb, int n)
    {
        // Complex S-matrix multiplication: Y_i = Σ_j S_ij · X_j
        // Expanded into Re/Im components:
        //   Y_re = S_re · X_re − S_im · X_im
        //   Y_im = S_re · X_im + S_im · X_re
        for (int outPort = 0; outPort < n; outPort++)
        {
            var reTerms = new List<string>();
            var imTerms = new List<string>();
            for (int inPort = 0; inPort < n; inPort++)
            {
                var sRe = $"s{outPort + 1}{inPort + 1}_re";
                var sIm = $"s{outPort + 1}{inPort + 1}_im";
                var xRe = $"V(port{inPort}_re)";
                var xIm = $"V(port{inPort}_im)";
                reTerms.Add($"{sRe}*{xRe} - {sIm}*{xIm}");
                imTerms.Add($"{sRe}*{xIm} + {sIm}*{xRe}");
            }
            sb.AppendLine($"        V(port{outPort}_re) <+ {string.Join(" + ", reTerms)};");
            sb.AppendLine($"        V(port{outPort}_im) <+ {string.Join(" + ", imTerms)};");
        }
    }

    /// <summary>
    /// Extracts (out, in) → S-parameter. Returns the map plus a flag indicating
    /// whether the heuristic fallback was used (so the caller can emit a WARNING).
    /// Throws when a pin has no <c>LogicalPin</c> (indicates an unfinished model).
    /// </summary>
    internal static (Dictionary<(int Out, int In), Complex> Map, bool UsedHeuristic) ExtractSParameters(
        Component comp, int wavelengthNm)
    {
        var result = new Dictionary<(int, int), Complex>();
        var pins = comp.PhysicalPins;

        foreach (var pin in pins)
        {
            if (pin.LogicalPin == null)
            {
                throw new InvalidOperationException(
                    $"Pin '{pin.Name}' on component '{comp.Name}' has no LogicalPin. " +
                    "The component model is incomplete — finish wiring the LogicalPins " +
                    "before exporting to Verilog-A.");
            }
        }

        if (!comp.WaveLengthToSMatrixMap.TryGetValue(wavelengthNm, out var sMatrix))
            return (ApplyHeuristicModel(comp), UsedHeuristic: true);

        var transfers = sMatrix.GetNonNullValues();

        for (int outIdx = 0; outIdx < pins.Count; outIdx++)
        {
            var outPin = pins[outIdx];
            for (int inIdx = 0; inIdx < pins.Count; inIdx++)
            {
                var inPin = pins[inIdx];
                var key = (inPin.LogicalPin!.IDInFlow, outPin.LogicalPin!.IDOutFlow);
                if (transfers.TryGetValue(key, out var transfer))
                    result[(outIdx, inIdx)] = transfer;
            }
        }

        return result.Count > 0 ? (result, false) : (ApplyHeuristicModel(comp), true);
    }

    private static Dictionary<(int, int), Complex> ApplyHeuristicModel(Component comp)
    {
        var result = new Dictionary<(int, int), Complex>();
        var name = (comp.NazcaFunctionName ?? comp.Name).ToLowerInvariant();
        int n = comp.PhysicalPins.Count;

        if (n == 2)
        {
            var loss = name.Contains("wg") || name.Contains("straight")
                ? WaveguideThroughputLossy
                : WaveguideThroughputIdeal;
            result[(0, 1)] = new Complex(loss, 0);
            result[(1, 0)] = new Complex(loss, 0);
        }
        else if (n == 3)
        {
            // Y-junction / 1x2 splitter: 50/50 split between out ports.
            result[(1, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(2, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(0, 1)] = new Complex(SplitAmplitude5050, 0);
            result[(0, 2)] = new Complex(SplitAmplitude5050, 0);
        }
        else if (n == 4)
        {
            // 2x2 directional coupler: 50/50 through + 50/50 cross.
            result[(2, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(3, 1)] = new Complex(SplitAmplitude5050, 0);
            result[(3, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(2, 1)] = new Complex(SplitAmplitude5050, 0);
        }
        else
        {
            // No physically-defensible default exists for arbitrary N-port components.
            // Emitting all-zero S-parameters would be a silent fallback — throw instead.
            throw new InvalidOperationException(
                $"Component '{comp.Name}' has {n} ports and no S-matrix at the requested " +
                "wavelength. The heuristic fallback only covers 2/3/4-port components. " +
                "Provide measured or simulated S-parameters via WaveLengthToSMatrixMap.");
        }

        return result;
    }
}
