using System.Globalization;
using System.Numerics;
using System.Text;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Writes a single Verilog-A module for one photonic component.
/// Uses S-matrix data when available; falls back to a physically-reasonable
/// heuristic for 2-/3-/4-port components with a loud warning in the module
/// header so the exported file documents the approximation.
/// </summary>
internal static class VerilogAModuleWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    internal static string Write(Component comp, string moduleName, int wavelengthNm)
    {
        var pins = comp.PhysicalPins;
        var portList = string.Join(", ", pins.Select((_, i) => $"port{i}"));
        var (sParams, usedHeuristic) = ExtractSParameters(comp, wavelengthNm);

        var sb = new StringBuilder();
        sb.AppendLine("`include \"disciplines.vams\"");
        sb.AppendLine();
        sb.AppendLine($"// Generated by Lunima — Component: {comp.Name}");
        if (!string.IsNullOrEmpty(comp.NazcaFunctionName))
            sb.AppendLine($"// PDK function: {comp.NazcaFunctionName}");
        sb.AppendLine($"// Ports: {pins.Count} | Wavelength: {wavelengthNm}nm");
        if (usedHeuristic)
        {
            sb.AppendLine("// WARNING: No S-matrix was available for this component at the given");
            sb.AppendLine($"//          wavelength ({wavelengthNm}nm). The transfer equations below");
            sb.AppendLine("//          are a lossless-coupler HEURISTIC — verify before trusting the");
            sb.AppendLine("//          simulation result. Provide measured or simulated S-parameters");
            sb.AppendLine("//          in the Lunima model to remove this approximation.");
        }
        sb.AppendLine();
        sb.AppendLine($"module {moduleName}({portList});");

        for (int i = 0; i < pins.Count; i++)
            sb.AppendLine($"    electrical port{i};  // {pins[i].Name}");

        sb.AppendLine();
        AppendSParameters(sb, sParams, pins.Count);
        sb.AppendLine("    analog begin");
        AppendTransferEquations(sb, pins.Count);
        sb.AppendLine("    end");
        sb.AppendLine("endmodule");

        return sb.ToString();
    }

    private static void AppendSParameters(StringBuilder sb, Dictionary<(int, int), Complex> sParams, int n)
    {
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++)
            {
                var s = sParams.TryGetValue((i, j), out var val) ? val : Complex.Zero;
                sb.AppendLine($"    parameter real s{i + 1}{j + 1}_mag = {s.Magnitude.ToString("G6", Inv)};");
                sb.AppendLine($"    parameter real s{i + 1}{j + 1}_phase = {s.Phase.ToString("G6", Inv)};");
            }
        sb.AppendLine();
    }

    private static void AppendTransferEquations(StringBuilder sb, int n)
    {
        for (int outPort = 0; outPort < n; outPort++)
        {
            var terms = new List<string>();
            for (int inPort = 0; inPort < n; inPort++)
            {
                var magParam = $"s{outPort + 1}{inPort + 1}_mag";
                var phaseParam = $"s{outPort + 1}{inPort + 1}_phase";
                terms.Add($"{magParam} * cos({phaseParam}) * V(port{inPort})");
            }
            sb.AppendLine($"        V(port{outPort}) <+ {string.Join(" + ", terms)};");
        }
    }

    /// <summary>
    /// Extracts (out, in) → S-parameter. Returns the map plus a flag indicating
    /// whether the heuristic fallback was used (so the caller can emit a WARNING).
    /// </summary>
    internal static (Dictionary<(int Out, int In), Complex> Map, bool UsedHeuristic) ExtractSParameters(
        Component comp, int wavelengthNm)
    {
        var result = new Dictionary<(int, int), Complex>();
        var pins = comp.PhysicalPins;

        if (!comp.WaveLengthToSMatrixMap.TryGetValue(wavelengthNm, out var sMatrix))
            return (ApplyHeuristicModel(comp), UsedHeuristic: true);

        var transfers = sMatrix.GetNonNullValues();

        for (int outIdx = 0; outIdx < pins.Count; outIdx++)
        {
            var outPin = pins[outIdx];
            if (outPin.LogicalPin == null) continue;

            for (int inIdx = 0; inIdx < pins.Count; inIdx++)
            {
                var inPin = pins[inIdx];
                if (inPin.LogicalPin == null) continue;

                var key = (inPin.LogicalPin.IDInFlow, outPin.LogicalPin.IDOutFlow);
                if (transfers.TryGetValue(key, out var transfer))
                    result[(outIdx, inIdx)] = transfer;
            }
        }

        return result.Count > 0 ? (result, false) : (ApplyHeuristicModel(comp), true);
    }

    private static Dictionary<(int, int), Complex> ApplyHeuristicModel(Component comp)
    {
        var result = new Dictionary<(int, int), Complex>();
        var name = (comp.NazcaFunctionName ?? comp.Name).ToLowerInvariant();
        int n = comp.PhysicalPins.Count;

        if (n == 2)
        {
            // Waveguide-like: reciprocal through-connection.
            double loss = name.Contains("wg") || name.Contains("straight") ? 0.95 : 0.99;
            result[(0, 1)] = new Complex(loss, 0);
            result[(1, 0)] = new Complex(loss, 0);
        }
        else if (n == 3)
        {
            // Y-junction / 1x2 splitter: 50/50 split.
            double split = Math.Sqrt(0.5);
            result[(1, 0)] = new Complex(split, 0);
            result[(2, 0)] = new Complex(split, 0);
            result[(0, 1)] = new Complex(split, 0);
            result[(0, 2)] = new Complex(split, 0);
        }
        else if (n == 4)
        {
            // 2x2 directional coupler: 50/50.
            double through = Math.Sqrt(0.5);
            double cross = Math.Sqrt(0.5);
            result[(2, 0)] = new Complex(through, 0);
            result[(3, 1)] = new Complex(through, 0);
            result[(3, 0)] = new Complex(cross, 0);
            result[(2, 1)] = new Complex(cross, 0);
        }
        // For n > 4 the heuristic has no sensible default — leave S empty so all
        // transfer equations evaluate to 0 and the simulator flags the issue.

        return result;
    }
}
