using System.Text;
using CAP_Core.Components.Connections;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Writes the top-level Verilog-A netlist and SPICE test bench for a Lunima design.
/// Shared nodes for connected pins; unconnected pins become external ports.
/// </summary>
internal static class VerilogANetlistWriter
{
    internal static (string Netlist, List<string> ExternalPorts) WriteTopLevel(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        string circuitName)
    {
        var nodeMap = BuildNodeMap(components, connections, out var externalPorts);
        var sb = new StringBuilder();

        sb.AppendLine($"// Top-level Verilog-A netlist: {circuitName}");
        sb.AppendLine($"// Generated by Lunima on {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine();

        foreach (var moduleName in components.Select(VerilogAIdentifier.For).Distinct())
            sb.AppendLine($"`include \"{moduleName}.va\"");
        sb.AppendLine();

        var extPortList = string.Join(", ", externalPorts);
        sb.AppendLine($"module {circuitName}({extPortList});");
        foreach (var port in externalPorts)
            sb.AppendLine($"    electrical {port};");

        var internalNodes = nodeMap.Values
            .SelectMany(d => d.Values)
            .Distinct()
            .Where(n => !externalPorts.Contains(n))
            .ToList();

        if (internalNodes.Count > 0)
            sb.AppendLine($"    electrical {string.Join(", ", internalNodes)};");
        sb.AppendLine();

        for (int i = 0; i < components.Count; i++)
        {
            var comp = components[i];
            var modName = VerilogAIdentifier.For(comp);
            var ports = comp.PhysicalPins.Select((_, idx) => nodeMap[i][idx]).ToList();
            sb.AppendLine($"    {modName} inst_{i}({string.Join(", ", ports)});  // {comp.Name}");
        }

        sb.AppendLine("endmodule");
        return (sb.ToString(), externalPorts);
    }

    private static Dictionary<int, Dictionary<int, string>> BuildNodeMap(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        out List<string> externalPorts)
    {
        var nodeMap = new Dictionary<int, Dictionary<int, string>>();
        int nodeCounter = 0;

        for (int i = 0; i < components.Count; i++)
        {
            nodeMap[i] = new Dictionary<int, string>();
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
                nodeMap[i][j] = $"n{nodeCounter++}";
        }

        foreach (var conn in connections)
        {
            var (startCompIdx, startPinIdx) = FindPinIndex(components, conn.StartPin);
            var (endCompIdx, endPinIdx) = FindPinIndex(components, conn.EndPin);

            if (startCompIdx < 0)
                throw new InvalidOperationException(
                    $"Connection start pin does not belong to any exported component. " +
                    $"Pin '{conn.StartPin.Name}' (id {conn.StartPin.PinId}) is orphan.");
            if (endCompIdx < 0)
                throw new InvalidOperationException(
                    $"Connection end pin does not belong to any exported component. " +
                    $"Pin '{conn.EndPin.Name}' (id {conn.EndPin.PinId}) is orphan.");

            var sharedNode = nodeMap[startCompIdx][startPinIdx];
            nodeMap[endCompIdx][endPinIdx] = sharedNode;
        }

        var connectedPins = new HashSet<Guid>(
            connections.SelectMany(c => new[] { c.StartPin.PinId, c.EndPin.PinId }));

        externalPorts = new List<string>();
        int portCounter = 0;
        for (int i = 0; i < components.Count; i++)
        {
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
            {
                var pin = components[i].PhysicalPins[j];
                if (!connectedPins.Contains(pin.PinId))
                {
                    var portName = $"ext_port{portCounter++}";
                    nodeMap[i][j] = portName;
                    externalPorts.Add(portName);
                }
            }
        }

        return nodeMap;
    }

    private static (int CompIdx, int PinIdx) FindPinIndex(
        IReadOnlyList<Component> components, PhysicalPin pin)
    {
        for (int i = 0; i < components.Count; i++)
        {
            var idx = components[i].PhysicalPins.IndexOf(pin);
            if (idx >= 0) return (i, idx);
        }
        return (-1, -1);
    }

    internal static string WriteSpiceTestBench(string circuitName, List<string> externalPorts)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"* SPICE test bench for {circuitName}");
        sb.AppendLine($"* Generated by Lunima — {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine($".include \"{circuitName}.va\"");
        sb.AppendLine();

        if (externalPorts.Count > 0)
            sb.AppendLine("* Optical power source at first external port (1V ≡ 1mW by convention)");

        for (int i = 0; i < externalPorts.Count; i++)
            sb.AppendLine($"V{i + 1} {externalPorts[i]} 0 DC {(i == 0 ? "1.0" : "0.0")}");

        sb.AppendLine();
        var portList = string.Join(" ", externalPorts.Append("0"));
        sb.AppendLine($"XDUT {portList} {circuitName}");
        sb.AppendLine();
        sb.AppendLine(".op");
        sb.AppendLine($".print OP {string.Join(" ", externalPorts.Select(p => $"V({p})"))}");
        sb.AppendLine(".end");

        return sb.ToString();
    }
}

/// <summary>
/// Produces a Verilog-identifier-safe name from a <see cref="Component"/>.
/// Uses <c>NazcaFunctionName</c> when present, otherwise <c>Name</c>.
/// Non-alphanumeric characters become underscores.
/// </summary>
internal static class VerilogAIdentifier
{
    internal static string For(Component comp)
    {
        var name = comp.NazcaFunctionName ?? comp.Name ?? "component";
        return System.Text.RegularExpressions.Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
    }
}
