using System.Globalization;
using System.Numerics;
using System.Text;
using CAP_Core.Components.Connections;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Exports photonic circuits to Verilog-A format for SPICE-based co-simulation.
/// Generates component library files (.va) and a top-level netlist.
/// </summary>
public class VerilogAExporter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    /// <summary>
    /// Exports a photonic circuit to Verilog-A files.
    /// </summary>
    /// <param name="components">All components in the design.</param>
    /// <param name="connections">All waveguide connections.</param>
    /// <param name="options">Export configuration options.</param>
    /// <returns>Export result with generated file contents.</returns>
    public VerilogAExportResult Export(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        VerilogAExportOptions options)
    {
        if (components == null || components.Count == 0)
            return VerilogAExportResult.Failure("No components in design.");

        try
        {
            var componentFiles = GenerateComponentLibrary(components, options.WavelengthNm);
            var (netlist, portNodes) = GenerateTopLevelNetlist(components, connections, options.CircuitName);
            var testBench = options.IncludeTestBench
                ? GenerateSpiceTestBench(options.CircuitName, portNodes)
                : string.Empty;

            return new VerilogAExportResult
            {
                Success = true,
                ComponentFiles = componentFiles,
                TopLevelNetlist = netlist,
                SpiceTestBench = testBench,
                CircuitName = options.CircuitName
            };
        }
        catch (Exception ex)
        {
            return VerilogAExportResult.Failure($"Export failed: {ex.Message}");
        }
    }

    private static Dictionary<string, string> GenerateComponentLibrary(
        IReadOnlyList<Component> components, int wavelengthNm)
    {
        var files = new Dictionary<string, string>(StringComparer.Ordinal);
        var generated = new HashSet<string>(StringComparer.Ordinal);

        foreach (var comp in components)
        {
            var moduleName = GetModuleName(comp);
            if (!generated.Add(moduleName))
                continue;

            var content = GenerateComponentModule(comp, moduleName, wavelengthNm);
            files[$"{moduleName}.va"] = content;
        }

        return files;
    }

    /// <summary>
    /// Generates a Verilog-A module for a single component.
    /// Uses S-matrix data when available, falls back to component-type heuristics.
    /// </summary>
    public static string GenerateComponentModule(Component comp, string moduleName, int wavelengthNm)
    {
        var pins = comp.PhysicalPins;
        if (pins.Count == 0)
            return $"// Component {moduleName} has no optical ports\n";

        var portList = string.Join(", ", pins.Select((p, i) => $"port{i}"));
        var sb = new StringBuilder();

        sb.AppendLine("`include \"disciplines.vams\"");
        sb.AppendLine();
        sb.AppendLine($"// Generated by Lunima — Component: {comp.Name}");
        if (!string.IsNullOrEmpty(comp.NazcaFunctionName))
            sb.AppendLine($"// PDK function: {comp.NazcaFunctionName}");
        sb.AppendLine($"// Ports: {pins.Count} optical ports | Wavelength: {wavelengthNm}nm");
        sb.AppendLine();
        sb.AppendLine($"module {moduleName}({portList});");

        foreach (var (pin, idx) in pins.Select((p, i) => (p, i)))
            sb.AppendLine($"    electrical port{idx};  // {pin.Name}");

        sb.AppendLine();
        AppendSParameters(sb, comp, wavelengthNm);

        sb.AppendLine("    analog begin");
        AppendTransferEquations(sb, comp, wavelengthNm);
        sb.AppendLine("    end");
        sb.AppendLine("endmodule");

        return sb.ToString();
    }

    private static void AppendSParameters(StringBuilder sb, Component comp, int wavelengthNm)
    {
        var sParams = ExtractSParameters(comp, wavelengthNm);
        int n = comp.PhysicalPins.Count;

        for (int i = 0; i < n; i++)
        for (int j = 0; j < n; j++)
        {
            var key = (i, j);
            var s = sParams.TryGetValue(key, out var val) ? val : Complex.Zero;
            sb.AppendLine($"    parameter real s{i + 1}{j + 1}_mag = {s.Magnitude.ToString("G6", Inv)};");
            sb.AppendLine($"    parameter real s{i + 1}{j + 1}_phase = {s.Phase.ToString("G6", Inv)};");
        }

        sb.AppendLine();
    }

    private static void AppendTransferEquations(StringBuilder sb, Component comp, int wavelengthNm)
    {
        int n = comp.PhysicalPins.Count;

        for (int outPort = 0; outPort < n; outPort++)
        {
            var terms = new List<string>();
            for (int inPort = 0; inPort < n; inPort++)
            {
                var magParam = $"s{outPort + 1}{inPort + 1}_mag";
                var phaseParam = $"s{outPort + 1}{inPort + 1}_phase";
                terms.Add($"{magParam} * cos({phaseParam}) * V(port{inPort})");
            }

            sb.AppendLine($"        V(port{outPort}) <+ {string.Join(" + ", terms)};");
        }
    }

    /// <summary>
    /// Extracts S-parameters from a component's S-matrix map.
    /// Returns matrix indexed by (output_port_index, input_port_index) = Complex S[out,in].
    /// Falls back to component-type heuristics when S-matrix data is unavailable.
    /// </summary>
    public static Dictionary<(int Out, int In), Complex> ExtractSParameters(
        Component comp, int wavelengthNm)
    {
        var result = new Dictionary<(int, int), Complex>();
        var pins = comp.PhysicalPins;

        if (pins.Count == 0 || !comp.WaveLengthToSMatrixMap.TryGetValue(wavelengthNm, out var sMatrix))
            return ApplyHeuristicModel(comp);

        var transfers = sMatrix.GetNonNullValues();

        for (int outIdx = 0; outIdx < pins.Count; outIdx++)
        {
            var outPin = pins[outIdx];
            if (outPin.LogicalPin == null) continue;

            for (int inIdx = 0; inIdx < pins.Count; inIdx++)
            {
                var inPin = pins[inIdx];
                if (inPin.LogicalPin == null) continue;

                var key = (inPin.LogicalPin.IDInFlow, outPin.LogicalPin.IDOutFlow);
                if (transfers.TryGetValue(key, out var transfer))
                    result[(outIdx, inIdx)] = transfer;
            }
        }

        return result.Count > 0 ? result : ApplyHeuristicModel(comp);
    }

    private static Dictionary<(int, int), Complex> ApplyHeuristicModel(Component comp)
    {
        var result = new Dictionary<(int, int), Complex>();
        var name = (comp.NazcaFunctionName ?? comp.Name).ToLowerInvariant();
        int n = comp.PhysicalPins.Count;

        if (n == 2)
        {
            // Waveguide: ideal through connection with minimal loss
            double loss = name.Contains("wg") || name.Contains("straight") ? 0.95 : 0.99;
            result[(0, 1)] = new Complex(loss, 0);
            result[(1, 0)] = new Complex(loss, 0);
        }
        else if (n == 3)
        {
            // Y-junction / 1x2 splitter: 50/50 split
            double split = Math.Sqrt(0.5);
            result[(1, 0)] = new Complex(split, 0);
            result[(2, 0)] = new Complex(split, 0);
            result[(0, 1)] = new Complex(split, 0);
            result[(0, 2)] = new Complex(split, 0);
        }
        else if (n == 4)
        {
            // 2x2 coupler: 50/50 coupling
            double through = Math.Sqrt(0.5);
            double cross = Math.Sqrt(0.5);
            result[(2, 0)] = new Complex(through, 0);
            result[(3, 1)] = new Complex(through, 0);
            result[(3, 0)] = new Complex(cross, 0);
            result[(2, 1)] = new Complex(cross, 0);
        }

        return result;
    }

    private static (string Netlist, List<string> ExternalPorts) GenerateTopLevelNetlist(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        string circuitName)
    {
        var nodeMap = BuildNodeMap(components, connections, out var externalPorts);
        var sb = new StringBuilder();

        sb.AppendLine($"// Top-level Verilog-A netlist: {circuitName}");
        sb.AppendLine($"// Generated by Lunima on {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine();

        foreach (var file in components.Select(GetModuleName).Distinct())
            sb.AppendLine($"`include \"{file}.va\"");
        sb.AppendLine();

        var extPortList = string.Join(", ", externalPorts);
        sb.AppendLine($"module {circuitName}({extPortList});");
        foreach (var port in externalPorts)
            sb.AppendLine($"    electrical {port};");

        var internalNodes = nodeMap.Values
            .SelectMany(d => d.Values)
            .Distinct()
            .Where(n => !externalPorts.Contains(n))
            .ToList();

        if (internalNodes.Count > 0)
            sb.AppendLine($"    electrical {string.Join(", ", internalNodes)};");

        sb.AppendLine();

        for (int i = 0; i < components.Count; i++)
        {
            var comp = components[i];
            var modName = GetModuleName(comp);
            var ports = comp.PhysicalPins.Select((_, idx) => nodeMap[i][idx]).ToList();
            sb.AppendLine($"    {modName} inst_{i}({string.Join(", ", ports)});  // {comp.Name}");
        }

        sb.AppendLine("endmodule");
        return (sb.ToString(), externalPorts);
    }

    private static Dictionary<int, Dictionary<int, string>> BuildNodeMap(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        out List<string> externalPorts)
    {
        var nodeMap = new Dictionary<int, Dictionary<int, string>>();
        int nodeCounter = 0;

        // Initialize all pins as unique nodes
        for (int i = 0; i < components.Count; i++)
        {
            nodeMap[i] = new Dictionary<int, string>();
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
                nodeMap[i][j] = $"n{nodeCounter++}";
        }

        // Merge nodes connected by waveguides
        foreach (var conn in connections)
        {
            var (startCompIdx, startPinIdx) = FindPinIndex(components, conn.StartPin);
            var (endCompIdx, endPinIdx) = FindPinIndex(components, conn.EndPin);

            if (startCompIdx < 0 || endCompIdx < 0) continue;

            var sharedNode = nodeMap[startCompIdx][startPinIdx];
            nodeMap[endCompIdx][endPinIdx] = sharedNode;
        }

        // External ports: pins not connected to any waveguide
        var connectedPins = new HashSet<Guid>(
            connections.SelectMany(c => new[] { c.StartPin.PinId, c.EndPin.PinId }));

        externalPorts = new List<string>();
        int portCounter = 0;
        for (int i = 0; i < components.Count; i++)
        {
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
            {
                var pin = components[i].PhysicalPins[j];
                if (!connectedPins.Contains(pin.PinId))
                {
                    var portName = $"ext_port{portCounter++}";
                    nodeMap[i][j] = portName;
                    externalPorts.Add(portName);
                }
            }
        }

        return nodeMap;
    }

    private static (int CompIdx, int PinIdx) FindPinIndex(
        IReadOnlyList<Component> components, PhysicalPin pin)
    {
        for (int i = 0; i < components.Count; i++)
        {
            var idx = components[i].PhysicalPins.IndexOf(pin);
            if (idx >= 0) return (i, idx);
        }
        return (-1, -1);
    }

    private static string GenerateSpiceTestBench(string circuitName, List<string> externalPorts)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"* SPICE test bench for {circuitName}");
        sb.AppendLine($"* Generated by Lunima — {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine($".include \"{circuitName}.va\"");
        sb.AppendLine();

        if (externalPorts.Count > 0)
            sb.AppendLine($"* Optical power source at input (1mW = 1V convention)");

        for (int i = 0; i < externalPorts.Count; i++)
            sb.AppendLine($"V{i + 1} {externalPorts[i]} 0 DC {(i == 0 ? "1.0" : "0.0")}");

        sb.AppendLine();
        var portList = string.Join(" ", externalPorts.Append("0"));
        sb.AppendLine($"XDUT {portList} {circuitName}");
        sb.AppendLine();
        sb.AppendLine(".op");
        sb.AppendLine($".print OP {string.Join(" ", externalPorts.Select(p => $"V({p})"))}");
        sb.AppendLine(".end");

        return sb.ToString();
    }

    private static string GetModuleName(Component comp)
    {
        var name = comp.NazcaFunctionName ?? comp.Name ?? "component";
        return SanitizeIdentifier(name);
    }

    public static string SanitizeIdentifier(string name) =>
        System.Text.RegularExpressions.Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
}
