using System.Globalization;
using System.Numerics;
using System.Text;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Writes a single Verilog-A module for one photonic component using the
/// twin-node complex amplitude model. Each optical port N is represented by
/// two electrical nodes (<c>portN_re</c> / <c>portN_im</c>) carrying the real
/// and imaginary parts of the complex field amplitude. Transfer equations
/// implement full complex S-matrix multiplication Y = S·X, preserving phase.
/// Falls back to a physically-reasonable heuristic for 2-/3-/4-port components
/// with a loud warning when no S-matrix is available.
/// </summary>
internal static class VerilogAModuleWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    // Heuristic transmission amplitudes used when no S-matrix is available.
    private const double WaveguideThroughputLossy = 0.95;     // Lossy straight waveguide (≈ 0.45 dB/segment)
    private const double WaveguideThroughputIdeal = 0.99;     // Near-ideal 2-port element
    private static readonly double SplitAmplitude5050 = Math.Sqrt(0.5);  // 50/50 power splitter

    internal static string Write(Component comp, string moduleName, int wavelengthNm)
    {
        var pins = comp.PhysicalPins;
        var portList = BuildPortList(pins.Count);
        var (sParams, usedHeuristic) = ExtractSParameters(comp, wavelengthNm);

        var sb = new StringBuilder();
        sb.AppendLine("`include \"disciplines.vams\"");
        sb.AppendLine();
        AppendComplexModelHeader(sb);
        sb.AppendLine($"// Generated by Lunima — Component: {comp.Name}");
        if (!string.IsNullOrEmpty(comp.NazcaFunctionName))
            sb.AppendLine($"// PDK function: {comp.NazcaFunctionName}");
        sb.AppendLine($"// Ports: {pins.Count} | Wavelength: {wavelengthNm}nm");
        if (usedHeuristic)
        {
            sb.AppendLine("// WARNING: No S-matrix was available for this component at the given");
            sb.AppendLine($"//          wavelength ({wavelengthNm}nm). The transfer equations below");
            sb.AppendLine("//          are a lossless-coupler HEURISTIC — verify before trusting the");
            sb.AppendLine("//          simulation result. Provide measured or simulated S-parameters");
            sb.AppendLine("//          in the Lunima model to remove this approximation.");
        }
        sb.AppendLine();
        sb.AppendLine($"module {moduleName}({portList});");

        AppendPortDeclarations(sb, pins);
        sb.AppendLine();
        AppendSParameters(sb, sParams, pins.Count);
        sb.AppendLine("    analog begin");
        AppendTransferEquations(sb, pins.Count);
        sb.AppendLine("    end");
        sb.AppendLine("endmodule");

        return sb.ToString();
    }

    private static void AppendComplexModelHeader(StringBuilder sb)
    {
        sb.AppendLine("// ======================================================================");
        sb.AppendLine("// Complex optical port model — Lunima twin-node convention:");
        sb.AppendLine("//   Each optical port N is represented by two electrical nodes:");
        sb.AppendLine("//     portN_re — real part of the complex field amplitude");
        sb.AppendLine("//     portN_im — imaginary part of the complex field amplitude");
        sb.AppendLine("//");
        sb.AppendLine("// Wave-based S-parameter formulation (current contributions):");
        sb.AppendLine("//   Each port has a z0 characteristic admittance to ground plus VCCS");
        sb.AppendLine("//   contributions for every S-matrix transfer. At node portN_re:");
        sb.AppendLine("//     I(portN_re) = V(portN_re)/z0  −  Σ_k (S_Nk_re·V(portk_re) − S_Nk_im·V(portk_im)) / z0");
        sb.AppendLine("//   (analogous for _im). Current-contributions avoid the DC-solve");
        sb.AppendLine("//   singularity that voltage contributions create on inout ports.");
        sb.AppendLine("//");
        sb.AppendLine("//   Optical power at port N: P ∝ V(portN_re)² + V(portN_im)²");
        sb.AppendLine("// ======================================================================");
        sb.AppendLine();
    }

    private static string BuildPortList(int n)
        => string.Join(", ", Enumerable.Range(0, n).SelectMany(i => new[] { $"port{i}_re", $"port{i}_im" }));

    private static void AppendPortDeclarations(StringBuilder sb, IList<PhysicalPin> pins)
    {
        for (int i = 0; i < pins.Count; i++)
            sb.AppendLine($"    inout port{i}_re, port{i}_im;");
        for (int i = 0; i < pins.Count; i++)
            sb.AppendLine($"    electrical port{i}_re, port{i}_im;  // {pins[i].Name}");
    }

    private static void AppendSParameters(StringBuilder sb, Dictionary<(int, int), Complex> sParams, int n)
    {
        sb.AppendLine("    parameter real z0 = 1.0;  // Port characteristic impedance (normalized units).");
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++)
            {
                var s = sParams.TryGetValue((i, j), out var val) ? val : Complex.Zero;
                sb.AppendLine($"    parameter real s{i + 1}{j + 1}_re = {s.Real.ToString("G6", Inv)};");
                sb.AppendLine($"    parameter real s{i + 1}{j + 1}_im = {s.Imaginary.ToString("G6", Inv)};");
            }
        sb.AppendLine();
    }

    private static void AppendTransferEquations(StringBuilder sb, int n)
    {
        // Convention documented in AppendComplexModelHeader — do not duplicate here.
        for (int p = 0; p < n; p++)
        {
            sb.AppendLine($"        I(port{p}_re) <+ V(port{p}_re) / z0;");
            sb.AppendLine($"        I(port{p}_im) <+ V(port{p}_im) / z0;");
        }
        for (int outPort = 0; outPort < n; outPort++)
        {
            for (int inPort = 0; inPort < n; inPort++)
            {
                var sRe = $"s{outPort + 1}{inPort + 1}_re";
                var sIm = $"s{outPort + 1}{inPort + 1}_im";
                var xRe = $"V(port{inPort}_re)";
                var xIm = $"V(port{inPort}_im)";
                sb.AppendLine($"        I(port{outPort}_re) <+ -({sRe}*{xRe} - {sIm}*{xIm}) / z0;");
                sb.AppendLine($"        I(port{outPort}_im) <+ -({sRe}*{xIm} + {sIm}*{xRe}) / z0;");
            }
        }
    }

    /// <summary>
    /// Extracts (out, in) → S-parameter via the shared <see cref="PirSMatrixExtractor"/>
    /// and falls back to a Verilog-A-specific heuristic when no S-matrix is
    /// registered for the given wavelength. The flag tells the caller whether
    /// the heuristic was used so a WARNING comment can be emitted.
    /// </summary>
    internal static (Dictionary<(int Out, int In), Complex> Map, bool UsedHeuristic) ExtractSParameters(
        Component comp, int wavelengthNm)
    {
        var extracted = PirSMatrixExtractor.TryExtract(comp, wavelengthNm);
        if (extracted != null)
            return (extracted, false);

        return (ApplyHeuristicModel(comp), UsedHeuristic: true);
    }

    private static Dictionary<(int, int), Complex> ApplyHeuristicModel(Component comp)
    {
        var result = new Dictionary<(int, int), Complex>();
        var name = (comp.NazcaFunctionName ?? comp.Name ?? "").ToLowerInvariant();
        int n = comp.PhysicalPins.Count;

        if (n == 2)
        {
            var loss = name.Contains("wg") || name.Contains("straight")
                ? WaveguideThroughputLossy
                : WaveguideThroughputIdeal;
            result[(0, 1)] = new Complex(loss, 0);
            result[(1, 0)] = new Complex(loss, 0);
        }
        else if (n == 3)
        {
            // Y-junction / 1x2 splitter: 50/50 split between out ports.
            result[(1, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(2, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(0, 1)] = new Complex(SplitAmplitude5050, 0);
            result[(0, 2)] = new Complex(SplitAmplitude5050, 0);
        }
        else if (n == 4)
        {
            // 2x2 directional coupler: 50/50 through + 50/50 cross.
            result[(2, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(3, 1)] = new Complex(SplitAmplitude5050, 0);
            result[(3, 0)] = new Complex(SplitAmplitude5050, 0);
            result[(2, 1)] = new Complex(SplitAmplitude5050, 0);
        }
        else
        {
            // No physically-defensible default exists for arbitrary N-port components.
            // Emitting all-zero S-parameters would be a silent fallback — throw instead.
            throw new InvalidOperationException(
                $"Component '{comp.Name}' has {n} ports and no S-matrix at the requested " +
                "wavelength. The heuristic fallback only covers 2/3/4-port components. " +
                "Provide measured or simulated S-parameters via WaveLengthToSMatrixMap.");
        }

        return result;
    }
}
