using System.Text;
using CAP_Core.Components.Connections;
using CAP_Core.Components.Core;

namespace CAP_Core.Export;

/// <summary>
/// Writes the top-level Verilog-A netlist and SPICE test bench for a Lunima design.
///
/// <para>
/// Uses the twin-node complex model: each optical pin maps to two electrical
/// nodes &lt;base&gt;_re and &lt;base&gt;_im. Connected pins share the same base node
/// name so both amplitude components are wired together. Unconnected pins
/// become external ports (pairs: <c>ext_portN_re</c>, <c>ext_portN_im</c>).
/// </para>
/// </summary>
internal static class VerilogANetlistWriter
{
    internal static (string Netlist, List<string> ExternalPortBases) WriteTopLevel(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        string circuitName)
    {
        // nodeMap[compIdx][pinIdx] = base name (e.g. "n0", "ext_port0")
        var nodeMap = BuildNodeMap(components, connections, out var externalPortBases);
        var sb = new StringBuilder();

        sb.AppendLine($"// Top-level Verilog-A netlist: {circuitName}");
        sb.AppendLine($"// Generated by Lunima on {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine("//");
        sb.AppendLine("// Complex-amplitude model: each optical net has twin electrical nodes,");
        sb.AppendLine("//   netName_re — real part of the optical amplitude");
        sb.AppendLine("//   netName_im — imaginary part of the optical amplitude");
        sb.AppendLine();

        foreach (var moduleName in components.Select(VerilogAIdentifier.For).Distinct())
            sb.AppendLine($"`include \"{moduleName}.va\"");
        sb.AppendLine();

        var extPortPairs = ExpandToPairs(externalPortBases);
        var extPortList = string.Join(", ", extPortPairs);
        sb.AppendLine($"module {circuitName}({extPortList});");
        foreach (var p in extPortPairs)
            sb.AppendLine($"    electrical {p};");

        var allBaseNodes = nodeMap.Values.SelectMany(d => d.Values).Distinct().ToList();
        var internalBases = allBaseNodes.Where(n => !externalPortBases.Contains(n)).ToList();
        if (internalBases.Count > 0)
        {
            var internalPairs = ExpandToPairs(internalBases);
            sb.AppendLine($"    electrical {string.Join(", ", internalPairs)};");
        }
        sb.AppendLine();

        for (int i = 0; i < components.Count; i++)
        {
            var comp = components[i];
            var modName = VerilogAIdentifier.For(comp);
            // Each pin maps to two ports: base_re, base_im
            var portArgs = comp.PhysicalPins
                .Select((_, idx) => nodeMap[i][idx])
                .SelectMany(baseName => new[] { $"{baseName}_re", $"{baseName}_im" });
            sb.AppendLine($"    {modName} inst_{i}({string.Join(", ", portArgs)});  // {comp.Name}");
        }

        sb.AppendLine("endmodule");
        return (sb.ToString(), externalPortBases);
    }

    private static List<string> ExpandToPairs(IEnumerable<string> baseNames)
    {
        var result = new List<string>();
        foreach (var b in baseNames)
        {
            result.Add($"{b}_re");
            result.Add($"{b}_im");
        }
        return result;
    }

    private static Dictionary<int, Dictionary<int, string>> BuildNodeMap(
        IReadOnlyList<Component> components,
        IReadOnlyList<WaveguideConnection> connections,
        out List<string> externalPortBases)
    {
        var nodeMap = new Dictionary<int, Dictionary<int, string>>();
        int nodeCounter = 0;

        for (int i = 0; i < components.Count; i++)
        {
            nodeMap[i] = new Dictionary<int, string>();
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
                nodeMap[i][j] = $"n{nodeCounter++}";
        }

        foreach (var conn in connections)
        {
            var (startCompIdx, startPinIdx) = FindPinIndex(components, conn.StartPin);
            var (endCompIdx, endPinIdx) = FindPinIndex(components, conn.EndPin);

            if (startCompIdx < 0)
                throw new InvalidOperationException(
                    $"Connection start pin does not belong to any exported component. " +
                    $"Pin '{conn.StartPin.Name}' (id {conn.StartPin.PinId}) is orphan.");
            if (endCompIdx < 0)
                throw new InvalidOperationException(
                    $"Connection end pin does not belong to any exported component. " +
                    $"Pin '{conn.EndPin.Name}' (id {conn.EndPin.PinId}) is orphan.");

            // Merge: make end pin share the same base node as the start pin
            var sharedBase = nodeMap[startCompIdx][startPinIdx];
            nodeMap[endCompIdx][endPinIdx] = sharedBase;
        }

        var connectedPins = new HashSet<Guid>(
            connections.SelectMany(c => new[] { c.StartPin.PinId, c.EndPin.PinId }));

        externalPortBases = new List<string>();
        int portCounter = 0;
        for (int i = 0; i < components.Count; i++)
        {
            for (int j = 0; j < components[i].PhysicalPins.Count; j++)
            {
                var pin = components[i].PhysicalPins[j];
                if (!connectedPins.Contains(pin.PinId))
                {
                    var portBase = $"ext_port{portCounter++}";
                    nodeMap[i][j] = portBase;
                    externalPortBases.Add(portBase);
                }
            }
        }

        return nodeMap;
    }

    private static (int CompIdx, int PinIdx) FindPinIndex(
        IReadOnlyList<Component> components, PhysicalPin pin)
    {
        for (int i = 0; i < components.Count; i++)
        {
            var idx = components[i].PhysicalPins.IndexOf(pin);
            if (idx >= 0) return (i, idx);
        }
        return (-1, -1);
    }

    internal static string WriteSpiceTestBench(string circuitName, List<string> externalPortBases)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"* SPICE test bench for {circuitName}");
        sb.AppendLine($"* Generated by Lunima — {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine("*");
        sb.AppendLine("* Complex-amplitude model convention:");
        sb.AppendLine("*   _re node: real part of optical amplitude (1V ≡ 1mW^0.5 by convention)");
        sb.AppendLine("*   _im node: imaginary part of optical amplitude");
        sb.AppendLine("* Input: port0_re = 1.0, port0_im = 0.0 → unit amplitude at 0° phase");
        sb.AppendLine($".include \"{circuitName}.va\"");
        sb.AppendLine();

        if (externalPortBases.Count > 0)
            sb.AppendLine("* Drive first external port with unit amplitude (real=1, imag=0)");

        int srcCounter = 1;
        for (int i = 0; i < externalPortBases.Count; i++)
        {
            var isFirst = i == 0;
            sb.AppendLine($"V{srcCounter++} {externalPortBases[i]}_re 0 DC {(isFirst ? "1.0" : "0.0")}");
            sb.AppendLine($"V{srcCounter++} {externalPortBases[i]}_im 0 DC 0.0");
        }

        sb.AppendLine();
        var allPairs = ExpandToPairs(externalPortBases);
        var portList = string.Join(" ", allPairs.Append("0"));
        sb.AppendLine($"XDUT {portList} {circuitName}");
        sb.AppendLine();
        sb.AppendLine(".op");
        sb.AppendLine($".print OP {string.Join(" ", allPairs.Select(p => $"V({p})"))}");
        sb.AppendLine(".end");

        return sb.ToString();
    }
}

/// <summary>
/// Produces a Verilog-identifier-safe name from a <see cref="Component"/>.
/// Uses <c>NazcaFunctionName</c> when present, otherwise <c>Name</c>.
/// Non-alphanumeric characters become underscores.
/// </summary>
internal static class VerilogAIdentifier
{
    internal static string For(Component comp)
    {
        var name = comp.NazcaFunctionName ?? comp.Name ?? "component";
        return System.Text.RegularExpressions.Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
    }
}
