name: Version Change

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (no 'v' prefix, e.g. 0.2.0)"
        required: true

jobs:
  create_version_pull_request:
    name: Create Version Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Version in csproj
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "CAP.Desktop/CAP.Desktop.csproj"
          version: ${{ github.event.inputs.version }}

      - name: Create and Push Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version/${{ github.event.inputs.version }}
          commit-message: "Update version to ${{ github.event.inputs.version }}"
          title: "chore: update version to ${{ github.event.inputs.version }}"
          body: "Updates project version to ${{ github.event.inputs.version }}."
