using System.Text;

namespace CAP_Core.Comparison;

/// <summary>
/// Exports a <see cref="ComparisonReport"/> to a human-readable text format.
/// </summary>
public static class ComparisonReportExporter
{
    /// <summary>
    /// Exports the report to a text string.
    /// </summary>
    public static string ExportToText(ComparisonReport report)
    {
        var sb = new StringBuilder();

        WriteHeader(sb, report);
        WriteMetricsTable(sb, report);
        WriteComponentBreakdown(sb, report);
        WriteDifferences(sb, report);
        WriteFooter(sb);

        return sb.ToString();
    }

    /// <summary>
    /// Exports the report to a file.
    /// </summary>
    public static async Task ExportToFileAsync(
        ComparisonReport report,
        string filePath)
    {
        var text = ExportToText(report);
        await File.WriteAllTextAsync(filePath, text);
    }

    private static void WriteHeader(StringBuilder sb, ComparisonReport report)
    {
        sb.AppendLine("═══════════════════════════════════════════════");
        sb.AppendLine("  Connect-A-PIC Pro — Design Comparison Report");
        sb.AppendLine("═══════════════════════════════════════════════");
        sb.AppendLine();
        sb.AppendLine($"  Design A: {report.DesignAName}");
        sb.AppendLine($"  Design B: {report.DesignBName}");
        sb.AppendLine();
    }

    private static void WriteMetricsTable(
        StringBuilder sb, ComparisonReport report)
    {
        var a = report.MetricsA;
        var b = report.MetricsB;

        sb.AppendLine("── Metrics Comparison ─────────────────────────");
        sb.AppendLine();
        sb.AppendLine($"  {"Metric",-35} {"A",8} {"B",8} {"Delta",8}");
        sb.AppendLine($"  {new string('─', 59)}");

        WriteRow(sb, "Components", a.ComponentCount, b.ComponentCount);
        WriteRow(sb, "Connections", a.ConnectionCount, b.ConnectionCount);
        WriteRow(sb, "Unique Component Types", a.UniqueComponentTypes, b.UniqueComponentTypes);
        WriteRow(sb, "Avg Connections/Component", a.AverageConnectionsPerComponent, b.AverageConnectionsPerComponent);
        WriteRow(sb, "Est. Total Loss (dB)", a.EstimatedTotalLossDb, b.EstimatedTotalLossDb);
        WriteRow(sb, "Complexity Score", a.ComplexityScore, b.ComplexityScore);
        sb.AppendLine();
    }

    private static void WriteRow(
        StringBuilder sb, string label, double valA, double valB)
    {
        var delta = valB - valA;
        var sign = delta >= 0 ? "+" : "";
        sb.AppendLine($"  {label,-35} {valA,8:F2} {valB,8:F2} {sign}{delta,7:F2}");
    }

    private static void WriteComponentBreakdown(
        StringBuilder sb, ComparisonReport report)
    {
        var allTypes = report.MetricsA.ComponentCountByType.Keys
            .Union(report.MetricsB.ComponentCountByType.Keys)
            .OrderBy(t => t);

        sb.AppendLine("── Component Breakdown ────────────────────────");
        sb.AppendLine();
        sb.AppendLine($"  {"Component Type",-35} {"A",8} {"B",8}");
        sb.AppendLine($"  {new string('─', 51)}");

        foreach (var type in allTypes)
        {
            int countA = report.MetricsA.ComponentCountByType
                .GetValueOrDefault(type, 0);
            int countB = report.MetricsB.ComponentCountByType
                .GetValueOrDefault(type, 0);
            sb.AppendLine($"  {type,-35} {countA,8} {countB,8}");
        }
        sb.AppendLine();
    }

    private static void WriteDifferences(
        StringBuilder sb, ComparisonReport report)
    {
        sb.AppendLine("── Topology Differences ───────────────────────");
        sb.AppendLine();

        if (report.Differences.Count == 0)
        {
            sb.AppendLine("  No topology differences found.");
        }
        else
        {
            foreach (var diff in report.Differences)
            {
                var marker = diff.Kind switch
                {
                    DifferenceKind.OnlyInA => "[A only]",
                    DifferenceKind.OnlyInB => "[B only]",
                    DifferenceKind.Modified => "[Changed]",
                    DifferenceKind.ConnectionOnlyInA => "[Conn A]",
                    DifferenceKind.ConnectionOnlyInB => "[Conn B]",
                    _ => "[?]"
                };
                sb.AppendLine($"  {marker,-10} {diff.Description}");
            }
        }
        sb.AppendLine();
    }

    private static void WriteFooter(StringBuilder sb)
    {
        sb.AppendLine("═══════════════════════════════════════════════");
        sb.AppendLine("  Generated by Connect-A-PIC Pro");
        sb.AppendLine("═══════════════════════════════════════════════");
    }
}
